before:
  hooks:
    - go mod download
builds:
- id: tkgi-kubectx
  main: ./cmd/tkgi-kubectx
  binary: tkgi-kubectx
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
    - arm64
    - ppc64le
    - s390x
  goarm: [6, 7]
archives:
- id: tkgi-kubectx-archive
  name_template: |-
    tkgi-kubectx_{{ .Tag }}_{{ .Os }}_{{ .Arch -}}
    {{- with .Arm -}}
      {{- if (eq . "6") -}}hf
      {{- else -}}v{{- . -}}
      {{- end -}}
    {{- end -}}
  builds:
    - tkgi-kubectx
  replacements:
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files: ["LICENSE"]
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
release:
  extra_files:
    - glob: ./tkgi-kubectx
