project_name: tkgi-kubectx

before:
  hooks:
  - rm -rf dist
  - go mod download
builds:
- id: tkgi-kubectx
  main: ./cmd/tkgi-kubectx
  binary: tkgi-kubectx
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
    - arm64
    - ppc64le
    - s390x
  goarm: [6, 7]

archives:
- id: tkgi-kubectx-archive
  name_template: |-
    {{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_
    {{- with .Arch -}}
      {{- if (eq . "386") -}}i386
      {{- else if (eq . "amd64") -}}x86_64
      {{- else -}}{{- . -}}
      {{- end -}}
    {{ end }}
    {{- with .Arm -}}
      {{- if (eq . "6") -}}hf
      {{- else -}}v{{- . -}}
      {{- end -}}
    {{- end -}}
  builds:
    - tkgi-kubectx
  format_overrides:
    - goos: windows
      format: zip
  files: ["LICENSE"]

release:
  prerelease: auto

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

brews:
- name: tkgi-kubectx
  tap:
    owner: jakuboskera
    name: homebrew-tap
  skip_upload: auto
  homepage: https://github.com/jakuboskera/tkgi-kubectx
  url_template: "https://github.com/jakuboskera/tkgi-kubectx/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  folder: Formula
  description: "Faster way to switch between clusters and namespaces in kubectl with support of tkgi login before switch"
  install: |
    bin.install "tkgi-kubectx"
  test: |
    system "#{bin}/tkgi-kubectx --version"

scoop:
  bucket:
    owner: jakuboskera
    name: scoop-bucket
  description: "Faster way to switch between clusters and namespaces in kubectl with support of tkgi login before switch"
  license: "Apache 2"
